### ISSUE TITLE
wrong label on the graph of 4x+15 (with delta_f & delta_x lines)

### ISSUE THREAD

**Issue by UpwardTrajectory** [learn-co-curriculum/introduction-to-derivatives-lab#10]
This only affects the labels on the graph, but if you don't make this change, it appears the slope is 1, when it is clearly a y = m*x+b linear with m = 4.
inside the block of code where we define delta_f_trace(...)
`name = 'delta f = ' + str(delta_x))`
should be:
`              name = 'delta f = ' + str(delta_f_value))`

**Comment by mas16** [comment]
Thank you UpwardTrajectory! This has been corrected.
