### ISSUE TITLE
test file doesn't match Jupyter lab

### ISSUE THREAD

**Issue by yoyothesheep** [learn-co-curriculum/introduction-to-derivatives-lab#3]
From AAQ: I actually had looked at the test file. Some of the objects that are imported from the Jupyter notebook and compared to numeric answers are functions or variables from the lesson (like output_at), but others (for example derivative_at_x_value_provided_tangent) do not appear in the lesson. What are these testing? I'm afraid my Python is not that advanced (though I do understand classes).

**Comment by cutterbuck** [comment]
not sure what happened -- i suppose those tests were from the earlier version of this lab? either way, it now has the correct tests for the Jupyter notebook
