### ISSUE TITLE
code does not run in the lab

### ISSUE THREAD

**Issue by alexxlu** [learn-co-curriculum/introduction-to-derivatives-lab#7]
here is the error msg from the running the code you provided in Line 17. I saw few people making comments that the code does run. not sure if it had been answered or addressed. could someone please help?

ValueErrorTraceback (most recent call last)
<ipython-input-17-69655da54796> in <module>()
      9 
     10 three_x_squared_minus_eleven_trace  = trace_values(x_values, y_values, mode = 'line')
---> 11 plot([three_x_squared_minus_eleven_trace], {'title': '3x^2 - 11'})

~/introduction-to-derivatives-lab-ds-apply-000/graph.py in plot(traces, layout)
     29 def plot(traces, layout = {}):
     30     if not isinstance(traces, list): raise TypeError('first argument must be a list.  Instead is', traces)
---> 31     plotly.offline.iplot({'data': traces, 'layout': layout})
     32 
     33 def build_layout(x_axis = None, y_axis = None, options = {}):

/opt/conda/lib/python3.6/site-packages/plotly/offline/offline.py in iplot(figure_or_data, show_link, link_text, validate, image, filename, image_width, image_height, config)
    334     config.setdefault('linkText', link_text)
    335 
--> 336     figure = tools.return_figure_from_figure_or_data(figure_or_data, validate)
    337 
    338     # Though it can add quite a bit to the display-bundle size, we include

/opt/conda/lib/python3.6/site-packages/plotly/tools.py in return_figure_from_figure_or_data(figure_or_data, validate_figure)
   1473 
   1474         try:
-> 1475             figure = Figure(**figure).to_dict()
   1476         except exceptions.PlotlyError as err:
   1477             raise exceptions.PlotlyError("Invalid 'figure_or_data' argument. "

/opt/conda/lib/python3.6/site-packages/plotly/graph_objs/_figure.py in __init__(self, data, layout, frames)
    312                         respective traces in the data attribute
    313         """
--> 314         super(Figure, self).__init__(data, layout, frames)
    315 
    316     def add_area(

/opt/conda/lib/python3.6/site-packages/plotly/basedatatypes.py in __init__(self, data, layout_plotly, frames)
    114 
    115         # ### Import traces ###
--> 116         data = self._data_validator.validate_coerce(data)
    117 
    118         # ### Save tuple of trace objects ###

/opt/conda/lib/python3.6/site-packages/_plotly_utils/basevalidators.py in validate_coerce(self, v)
   1960                         invalid_els.append(v_el)
   1961                     else:
-> 1962                         trace = self.class_map[trace_type](**v_copy)
   1963                         res.append(trace)
   1964                 else:

/opt/conda/lib/python3.6/site-packages/plotly/graph_objs/_scatter.py in __init__(self, arg, cliponaxis, connectgaps, customdata, customdatasrc, dx, dy, error_x, error_y, fill, fillcolor, hoverinfo, hoverinfosrc, hoverlabel, hoveron, hovertext, hovertextsrc, ids, idssrc, legendgroup, line, marker, mode, name, opacity, r, rsrc, selected, selectedpoints, showlegend, stream, t, text, textfont, textposition, textpositionsrc, textsrc, tsrc, uid, unselected, visible, x, x0, xaxis, xcalendar, xsrc, y, y0, yaxis, ycalendar, ysrc, **kwargs)
   2083         self.marker = marker if marker is not None else _v
   2084         _v = arg.pop('mode', None)
-> 2085         self.mode = mode if mode is not None else _v
   2086         _v = arg.pop('name', None)
   2087         self.name = name if name is not None else _v

/opt/conda/lib/python3.6/site-packages/plotly/basedatatypes.py in __setattr__(self, prop, value)
   2702                 prop in self._validators):
   2703             # Let known properties and private properties through
-> 2704             super(BasePlotlyType, self).__setattr__(prop, value)
   2705         else:
   2706             # Raise error on unknown public properties

/opt/conda/lib/python3.6/site-packages/plotly/graph_objs/_scatter.py in mode(self, val)
    828     @mode.setter
    829     def mode(self, val):
--> 830         self['mode'] = val
    831 
    832     # name

/opt/conda/lib/python3.6/site-packages/plotly/basedatatypes.py in __setitem__(self, prop, value)
   2674             # ### Handle simple property ###
   2675             else:
-> 2676                 self._set_prop(prop, value)
   2677 
   2678         # Handle non-scalar case

/opt/conda/lib/python3.6/site-packages/plotly/basedatatypes.py in _set_prop(self, prop, val)
   2904         # ------------
   2905         validator = self._validators.get(prop)
-> 2906         val = validator.validate_coerce(val)
   2907 
   2908         # val is None

/opt/conda/lib/python3.6/site-packages/_plotly_utils/basevalidators.py in validate_coerce(self, v)
   1508             validated_v = self.vc_scalar(v)
   1509             if validated_v is None:
-> 1510                 self.raise_invalid_val(v)
   1511 
   1512             v = validated_v

/opt/conda/lib/python3.6/site-packages/_plotly_utils/basevalidators.py in raise_invalid_val(self, v)
    214             typ=type_str(v),
    215             v=repr(v),
--> 216             valid_clr_desc=self.description()))
    217 
    218     def raise_invalid_elements(self, invalid_els):

ValueError: 
    Invalid value of type 'builtins.str' received for the 'mode' property of scatter
        Received value: 'line'

    The 'mode' property is a flaglist and may be specified
    as a string containing:
      - Any combination of ['lines', 'markers', 'text'] joined with '+' characters
        (e.g. 'lines+markers')
        OR exactly one of ['none'] (e.g. 'none')

**Comment by ericwithac** [comment]
I get the same issue
